DROP TABLE IF EXISTS posts;

CREATE TABLE posts (
    id      INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title   TEXT NOT NULL,
    content TEXT NOT NULL
);

DROP TABLE IF EXISTS socio;
CREATE TABLE socio (
    id_socio INTEGER PRIMARY KEY AUTOINCREMENT,
    nombre   TEXT NOT NULL,
    Telefono TEXT NOT NULL,
    Correoe  TEXT NOT NULL,
    Direccion TEXT NOT NULL,
    Colonia TEXT NOT NULL,
    Ciudad TEXT NOT NULL,
    Estado TEXT NOT NULL, 
    Codpos TEXT NOT NULL,
    Miembro_desde TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
